[theme]
primaryColor = "#8B4513"
backgroundColor = "#F5F5DC"
secondaryBackgroundColor = "#D2B48C"
textColor = "#212F3D"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
