DEEPSEEK_API_KEY = "sk-555051006a4740198a32c8f16b27ab62"
SUPABASE_URL = "https://sdbjypczhfyzzygzmvzq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkYmp5cGN6aGZ5enp5Z3ptdnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcyMzg5MzEsImV4cCI6MjA4MjgxNDkzMX0.7zLMpcgeTz_DUNTpbtNovH1FB06Dx6oKqZXZyqOYzDM"
